const path = require('path');
const dotenv = require('dotenv');
const { Pool } = require('pg');
const { put, list, get } = require('@vercel/blob');

dotenv.config({ path: path.resolve(__dirname, '../client/.env.local') });
dotenv.config({ path: path.resolve(__dirname, '../.env') });

const pool = new Pool({
  host: process.env.DB_HOST || '127.0.0.1',
  port: parseInt(process.env.DB_PORT || '5433', 10),
  user: process.env.DB_USER || 'postgres',
  password: process.env.DB_PASSWORD || 'HiLosGeht123',
  database: process.env.DB_NAME || 'postgres',
});

// Equipment IDs
const MACH_A_ID  = '11111111-1111-1111-1111-111111111103'; // Machine A (Joseph Mbogo) - JCB 3654401
const MACH_B_ID  = '11111111-1111-1111-1111-111111111109'; // Machine B (Freddy Mutuma) - JCB 3654406
const TIPPER_ID  = '11111111-1111-1111-1111-111111111107'; // Tipper Truck (Felix Maore) - Isuzu FVZ 34

// Operator IDs
const JOSEPH_ID  = '22222222-2222-2222-2222-222222222201';
const FREDDY_ID  = '22222222-2222-2222-2222-222222222202';
const FELIX_ID   = '22222222-2222-2222-2222-222222222203';

// Aug 19 to Sep 17 Operational Logs extracted from PDF and WhatsApp verification
const PDF_EARLY_LOGS = [
  // Aug 19
  {
    id: 'log-20260819-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 4.1,
    end_meter: 10.4,
    hours_worked: 6.3,
    fuel_amount: 92.12,
    start_fuel_reading: 92.12,
    end_fuel_reading: null,
    work_description: 'Initial backhoe startup & deployment - 92.12 L refilled (meter 4.1 to 10.4)',
    date_submitted: '2026-08-19T18:00:00Z',
    verification_status: 'APPROVED',
  },

  // Aug 20
  {
    id: 'log-20260820-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 10.4,
    end_meter: 18.4,
    hours_worked: 8.0,
    fuel_amount: 0,
    work_description: 'Full day backhoe excavation shift - 8.0 hrs worked (meter 10.4 to 18.4)',
    date_submitted: '2026-08-20T17:47:00Z',
    verification_status: 'APPROVED',
  },
  {
    id: 'log-20260820-felix',
    staff_id: FELIX_ID,
    staff_name: 'Felix Maore',
    operator_name: 'Felix Maore',
    staff_email: 'felix.maore@hilosgeht.co.ke',
    operator_email: 'felix.maore@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-3.svg',
    staff_avatar: '/avatars/avatar-3.svg',
    equipment_id: TIPPER_ID,
    equipment_name: 'Isuzu FVZ 34 15-Ton Tipper Truck',
    equipment_model: 'Isuzu FVZ 34',
    equipment_category: 'Tipper',
    start_meter: 512.8,
    end_meter: 520.8,
    hours_worked: 8.0,
    fuel_amount: 317.49,
    materials_received: '17 trips soil haulage at Nyambene Hospital',
    work_description: 'Materials haulage at Nyambene Hospital project - 17 trips completed, fuel refill 317.49',
    date_submitted: '2026-08-20T17:51:00Z',
    verification_status: 'APPROVED',
  },

  // Aug 21
  {
    id: 'log-20260821-felix',
    staff_id: FELIX_ID,
    staff_name: 'Felix Maore',
    operator_name: 'Felix Maore',
    staff_email: 'felix.maore@hilosgeht.co.ke',
    operator_email: 'felix.maore@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-3.svg',
    staff_avatar: '/avatars/avatar-3.svg',
    equipment_id: TIPPER_ID,
    equipment_name: 'Isuzu FVZ 34 15-Ton Tipper Truck',
    equipment_model: 'Isuzu FVZ 34',
    equipment_category: 'Tipper',
    start_meter: 520.8,
    end_meter: 523.8,
    hours_worked: 3.0,
    fuel_amount: 0,
    materials_received: '2 trips kokoto (quarry ballast)',
    work_description: 'Quarry ballast delivery - 2 trips kokoto hauled',
    date_submitted: '2026-08-21T19:12:00Z',
    verification_status: 'APPROVED',
  },
  {
    id: 'log-20260821-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 18.5,
    end_meter: 25.5,
    hours_worked: 7.0,
    fuel_amount: 0,
    work_description: 'Mukuri site preparation - 7.0 hrs worked (meter 18.5 to 25.5)',
    date_submitted: '2026-08-21T18:08:00Z',
    verification_status: 'APPROVED',
  },

  // Aug 22
  {
    id: 'log-20260822-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 25.9,
    end_meter: 32.9,
    hours_worked: 7.0,
    fuel_amount: 0,
    work_description: 'Site excavation - 7.0 hrs worked (front tyre puncture repaired KES 500)',
    date_submitted: '2026-08-22T17:45:00Z',
    verification_status: 'APPROVED',
  },

  // Aug 24
  {
    id: 'log-20260824-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 32.9,
    end_meter: 40.9,
    hours_worked: 8.0,
    fuel_amount: 0,
    work_description: 'Full day site works - 8.0 hrs worked',
    date_submitted: '2026-08-24T19:20:00Z',
    verification_status: 'APPROVED',
  },

  // Aug 27
  {
    id: 'log-20260827-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 40.9,
    end_meter: 48.4,
    hours_worked: 7.5,
    fuel_amount: 111.50,
    start_fuel_reading: 44.5,
    end_fuel_reading: 47.3,
    work_description: 'Backhoe excavation - 7.5 hrs worked, fuel refilled 111.50 L, greasing done',
    date_submitted: '2026-08-27T19:38:00Z',
    verification_status: 'APPROVED',
  },

  // Aug 28
  {
    id: 'log-20260828-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 48.4,
    end_meter: 54.4,
    hours_worked: 6.0,
    fuel_amount: 0,
    work_description: 'Daily backhoe operations (low network area) - 6.0 hrs worked',
    date_submitted: '2026-08-28T18:00:00Z',
    verification_status: 'APPROVED',
  },

  // Aug 29
  {
    id: 'log-20260829-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 57.4,
    end_meter: 65.4,
    hours_worked: 8.0,
    fuel_amount: 22.36,
    work_description: 'Full day shift - 8.0 hrs worked, fuel refilled 22.36 L (KES 5,000)',
    date_submitted: '2026-08-29T16:38:00Z',
    verification_status: 'APPROVED',
  },

  // Aug 31
  {
    id: 'log-20260831-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 69.2,
    end_meter: 72.2,
    hours_worked: 3.0,
    fuel_amount: 0,
    work_description: 'Makutano trenching contract - 3.0 hrs worked (meter 69.2 to 72.2)',
    date_submitted: '2026-08-31T20:07:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 02
  {
    id: 'log-20260902-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 72.2,
    end_meter: 78.2,
    hours_worked: 6.0,
    fuel_amount: 0,
    work_description: 'Mukuri site relocation & groundwork - 6.0 hrs worked',
    date_submitted: '2026-09-02T18:10:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 03
  {
    id: 'log-20260903-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 85.1,
    end_meter: 94.1,
    hours_worked: 9.0,
    fuel_amount: 118.26,
    start_fuel_reading: 85.1,
    end_fuel_reading: 94.3,
    work_description: 'Extended backhoe operations - 9.0 hrs worked, fuel refilled 118.26 L',
    date_submitted: '2026-09-03T19:02:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 04
  {
    id: 'log-20260904-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 94.5,
    end_meter: 100.5,
    hours_worked: 6.0,
    fuel_amount: 0,
    work_description: 'Daily trenching operations - 6.0 hrs worked',
    date_submitted: '2026-09-04T18:00:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 05
  {
    id: 'log-20260905-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 107.1,
    end_meter: 113.1,
    hours_worked: 6.0,
    fuel_amount: 0,
    work_description: 'Transit & KeNHA field operations via Embu - 6.0 hrs worked',
    date_submitted: '2026-09-05T18:05:00Z',
    verification_status: 'APPROVED',
  },
  {
    id: 'log-20260905-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 110.8,
    end_meter: 116.4,
    hours_worked: 5.6,
    fuel_amount: 116.97,
    start_fuel_reading: 110.8,
    end_fuel_reading: 116.4,
    work_description: 'Joseph onboarding field shift - 5.6 hrs worked, fuel refilled 116.97 L',
    date_submitted: '2026-09-05T17:53:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 06
  {
    id: 'log-20260906-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 116.9,
    end_meter: 122.9,
    hours_worked: 6.0,
    fuel_amount: 0,
    work_description: 'Sunday site clearing - 6.0 hrs worked (meter 116.9 to 122.9)',
    date_submitted: '2026-09-06T15:34:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 07
  {
    id: 'log-20260907-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 113.1,
    end_meter: 118.3,
    hours_worked: 5.2,
    fuel_amount: 0,
    work_description: 'Site operations - 5.2 hrs worked',
    date_submitted: '2026-09-07T15:56:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 08
  {
    id: 'log-20260908-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 122.9,
    end_meter: 130.9,
    hours_worked: 8.0,
    fuel_amount: 0,
    work_description: 'Full day deployment - billed per day rate (8.0 hrs, meter 125.6 morning)',
    date_submitted: '2026-09-08T18:00:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 09 - SERVICE MILESTONE
  {
    id: 'log-20260909-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 130.9,
    end_meter: 134.4,
    hours_worked: 3.5,
    fuel_amount: 0,
    work_description: 'Site operations & scheduled service milestone conducted at 134.4 engine hours',
    date_submitted: '2026-09-09T17:23:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 10
  {
    id: 'log-20260910-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 118.3,
    end_meter: 124.3,
    hours_worked: 6.0,
    fuel_amount: 0,
    work_description: 'Backhoe operations - 6.0 hrs worked (meter 14.3 morning, 16.2 at 1pm)',
    date_submitted: '2026-09-10T18:02:00Z',
    verification_status: 'APPROVED',
  },
  {
    id: 'log-20260910-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 134.4,
    end_meter: 142.4,
    hours_worked: 8.0,
    fuel_amount: 0,
    work_description: 'Full day deployment - billed per day rate (8.0 hrs)',
    date_submitted: '2026-09-10T18:00:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 11
  {
    id: 'log-20260911-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 124.3,
    end_meter: 130.6,
    hours_worked: 6.3,
    fuel_amount: 0,
    work_description: 'Two-stage field excavation - 6.3 hrs worked',
    date_submitted: '2026-09-11T18:00:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 12
  {
    id: 'log-20260912-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 130.6,
    end_meter: 137.1,
    hours_worked: 6.5,
    fuel_amount: 0,
    work_description: 'Backhoe excavation - 6 hrs 30 mins worked',
    date_submitted: '2026-09-12T22:17:00Z',
    verification_status: 'APPROVED',
  },
  {
    id: 'log-20260912-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 142.4,
    end_meter: 145.4,
    hours_worked: 3.0,
    fuel_amount: 0,
    work_description: 'Late arrival site shift - 3.0 hrs worked',
    date_submitted: '2026-09-12T19:46:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 13
  {
    id: 'log-20260913-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 145.4,
    end_meter: 152.4,
    hours_worked: 7.0,
    fuel_amount: 0,
    work_description: 'Sunday excavation and clearing - 7.0 hrs worked (meter 157.9 to 164.9)',
    date_submitted: '2026-09-13T18:25:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 14
  {
    id: 'log-20260914-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 137.1,
    end_meter: 145.1,
    hours_worked: 8.0,
    fuel_amount: 72.22,
    work_description: 'Full day shift - 8.0 hrs worked, fuel refilled KES 13,000 (~72.22 L)',
    date_submitted: '2026-09-14T20:19:00Z',
    verification_status: 'APPROVED',
  },
  {
    id: 'log-20260914-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 152.4,
    end_meter: 160.4,
    hours_worked: 8.0,
    fuel_amount: 55.55,
    work_description: 'Full day foundation excavation - 8.0 hrs worked, fuel refilled KES 10,000 (~55.55 L)',
    date_submitted: '2026-09-14T20:19:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 15
  {
    id: 'log-20260915-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 145.1,
    end_meter: 151.1,
    hours_worked: 6.0,
    fuel_amount: 0,
    work_description: 'Machine B operations officially designated - 6.0 hrs worked',
    date_submitted: '2026-09-15T19:12:00Z',
    verification_status: 'APPROVED',
  },
  {
    id: 'log-20260915-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 160.4,
    end_meter: 166.9,
    hours_worked: 6.5,
    fuel_amount: 0,
    work_description: 'Machine A operations officially designated - 6.5 hrs worked',
    date_submitted: '2026-09-15T19:15:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 16
  {
    id: 'log-20260916-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 151.1,
    end_meter: 156.1,
    hours_worked: 5.0,
    fuel_amount: 0,
    work_description: 'Field trenching - 5.0 hrs worked (in work at 2:14pm)',
    date_submitted: '2026-09-16T18:00:00Z',
    verification_status: 'APPROVED',
  },
  {
    id: 'log-20260916-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 166.9,
    end_meter: 174.4,
    hours_worked: 7.5,
    fuel_amount: 0,
    work_description: 'Site excavation - 7.5 hrs worked (meter 183.6 to 191.1)',
    date_submitted: '2026-09-16T18:00:00Z',
    verification_status: 'APPROVED',
  },

  // Sep 17
  {
    id: 'log-20260917-fred',
    staff_id: FREDDY_ID,
    staff_name: 'Fredrick Mutuma',
    operator_name: 'Fredrick Mutuma',
    staff_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_email: 'fredrick.mutuma@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-2.svg',
    staff_avatar: '/avatars/avatar-2.svg',
    equipment_id: MACH_B_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine B)',
    equipment_model: 'JCB 3DX - 3654406',
    equipment_category: 'Backhoe',
    start_meter: 156.1,
    end_meter: 161.1,
    hours_worked: 5.0,
    fuel_amount: 0,
    work_description: 'Site operations - 5.0 hrs worked',
    date_submitted: '2026-09-17T20:15:00Z',
    verification_status: 'APPROVED',
  },
  {
    id: 'log-20260917-joseph',
    staff_id: JOSEPH_ID,
    staff_name: 'Joseph Mbogo',
    operator_name: 'Joseph Mbogo',
    staff_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_email: 'joseph.mbogo@hilosgeht.co.ke',
    operator_avatar: '/avatars/avatar-1.svg',
    staff_avatar: '/avatars/avatar-1.svg',
    equipment_id: MACH_A_ID,
    equipment_name: 'JCB 3DX Backhoe Loader (Machine A)',
    equipment_model: 'JCB 3DX - 3654401',
    equipment_category: 'Backhoe',
    start_meter: 174.4,
    end_meter: 181.5,
    hours_worked: 7.1,
    fuel_amount: 0,
    work_description: 'Dual shift excavation - 7.1 hrs worked (4.1 hrs morning + 3.0 hrs afternoon)',
    date_submitted: '2026-09-17T18:06:00Z',
    verification_status: 'APPROVED',
  },
];

const CAROLINE_PAYMENTS = [
  {
    id: '44444444-4444-4444-4444-444444444401',
    physical_asset_id: MACH_B_ID,
    customer_id: null,
    client_name: 'Caroline',
    client_phone: '+254717186396',
    client_email: 'caroline.client@hilosgeht.co.ke',
    status: 'CONFIRMED',
    preferred_contact: 'WHATSAPP',
    total_amount: 71000.00,
    daily_rate: 15000.00,
    notes: 'Equipment operations payment - KES 71,000 received (August 20, 2026)',
    booking_period: '[2026-08-20 00:00:00+00, 2026-08-25 00:00:00+00)',
    created_at: '2026-08-20T09:00:00Z',
  },
  {
    id: '44444444-4444-4444-4444-444444444402',
    physical_asset_id: MACH_B_ID,
    customer_id: null,
    client_name: 'Caroline',
    client_phone: '+254717186396',
    client_email: 'caroline.client@hilosgeht.co.ke',
    status: 'CONFIRMED',
    preferred_contact: 'WHATSAPP',
    total_amount: 10000.00,
    daily_rate: 10000.00,
    notes: 'Equipment operations payment - KES 10,000 received (August 27, 2026)',
    booking_period: '[2026-08-27 00:00:00+00, 2026-08-28 00:00:00+00)',
    created_at: '2026-08-27T09:00:00Z',
  },
];

async function run() {
  console.log('--- ADDING AUGUST 19 - SEPTEMBER 17 DATA TO POSTGRESQL ---');
  const client = await pool.connect();
  try {
    await client.query('BEGIN');

    // 1. Insert Caroline payments into reservations table
    for (const res of CAROLINE_PAYMENTS) {
      await client.query(`
        INSERT INTO public.reservations (
          id, physical_asset_id, customer_id, client_name, client_phone, client_email,
          status, preferred_contact, total_amount, daily_rate, notes, booking_period, created_at, updated_at
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12::tstzrange, $13, NOW()
        ) ON CONFLICT (id) DO UPDATE SET
          total_amount = EXCLUDED.total_amount,
          notes = EXCLUDED.notes;
      `, [
        res.id, res.physical_asset_id, res.customer_id, res.client_name, res.client_phone, res.client_email,
        res.status, res.preferred_contact, res.total_amount, res.daily_rate, res.notes, res.booking_period, res.created_at
      ]);
    }
    console.log('✅ Caroline payments added to reservations table');

    // 2. Insert PDF_EARLY_LOGS into public.staff_logs
    for (const log of PDF_EARLY_LOGS) {
      await client.query(`
        INSERT INTO public.staff_logs (
          staff_id, equipment_id, start_meter, end_meter, work_description,
          fuel_amount, start_fuel_reading, end_fuel_reading, materials_received,
          date_submitted, verification_status
        ) VALUES (
          $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
        );
      `, [
        log.staff_id,
        log.equipment_id,
        log.start_meter,
        log.end_meter,
        log.work_description,
        log.fuel_amount,
        log.start_fuel_reading || null,
        log.end_fuel_reading || null,
        log.materials_received || null,
        log.date_submitted,
        log.verification_status,
      ]);
    }
    console.log(`✅ ${PDF_EARLY_LOGS.length} earlier logs added to public.staff_logs in PostgreSQL`);

    await client.query('COMMIT');

    // Count all logs in PostgreSQL
    const countRes = await client.query('SELECT count(*) FROM public.staff_logs');
    console.log(`📊 TOTAL OPERATIONAL LOGS IN POSTGRESQL NOW: ${countRes.rows[0].count}`);

    // Fetch all logs from PostgreSQL to save full unbroken history to Vercel Blob
    const allDbLogsRes = await client.query(`
      SELECT 
        l.id, l.staff_id, l.equipment_id, l.start_meter, l.end_meter,
        (l.end_meter - l.start_meter) as hours_worked,
        l.work_description, l.fuel_amount, l.start_fuel_reading, l.end_fuel_reading,
        l.fuel_proof_image, l.materials_received, l.date_submitted, l.verification_status,
        COALESCE(p.full_name, 'Certified Operator') as staff_name,
        COALESCE(p.full_name, 'Certified Operator') as operator_name,
        COALESCE(p.email, 'operator@hilosgeht.co.ke') as staff_email,
        COALESCE(p.email, 'operator@hilosgeht.co.ke') as operator_email,
        p.avatar_url as operator_avatar,
        p.avatar_url as staff_avatar,
        COALESCE(a.name, 'Heavy Machinery') as equipment_name,
        COALESCE(a.model, 'Asset') as equipment_model,
        COALESCE(a.category, 'Heavy Equipment') as equipment_category
      FROM public.staff_logs l
      LEFT JOIN public.profiles p ON l.staff_id = p.id
      LEFT JOIN public.physical_assets a ON l.equipment_id = a.id
      ORDER BY l.date_submitted ASC;
    `);

    const allLogs = allDbLogsRes.rows;

    const token = process.env.BLOB_READ_WRITE_TOKEN;
    if (token) {
      console.log('--- UPDATING VERCEL BLOB STORAGE (system/staff_logs.json) ---');
      await put('system/staff_logs.json', JSON.stringify(allLogs, null, 2), {
        access: 'private',
        token,
        contentType: 'application/json',
        addRandomSuffix: false,
        allowOverwrite: true,
      });
      console.log(`✅ Vercel Blob updated with all ${allLogs.length} logs!`);
    } else {
      console.log('⚠️ BLOB_READ_WRITE_TOKEN not set, skipping Vercel Blob sync');
    }

  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Error during data addition:', err);
    throw err;
  } finally {
    client.release();
    await pool.end();
  }
}

run().catch(console.error);
